[tool.poetry]
name = "resume"
version = "0.1.0"
description = ""
authors = ["Wesley Mendes <wesley@wesleymendes.com.br>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.1.2"
djangorestframework = "^3.12.1"
Markdown = "^3.3.2"
python-decouple = "^3.3"
psycopg2-binary = "^2.8.6"
djangorestframework-simplejwt = "^4.6.0"
django-extensions = "^3.0.9"

[tool.poetry.dev-dependencies]
mypy = "^0.790"
black = "^20.8b1"
factory-boy = "^3.1.0"
Faker = "^4.14.0"
flake8 = "^3.8.4"
ipdb = "^0.13.4"
pytest = "^6.1.1"
pytest-django = "^4.1.0"
pytest-flake8 = "^1.0.6"
requests = "^2.24.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
